name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release binary
        run: cargo build --release
      
      - name: List release directory
        run: ls -l target/release

      - name: Package binary
        run: |
          BIN_NAME="rusty_rolodex"
          if [ ! -f target/release/$BIN_NAME ]; then
            echo "❌ Error: Binary '$BIN_NAME' not found in target/release"
            exit 1
          fi
          tar czf rusty-rolodex-${{ github.ref_name }}-ubuntu-x86_64.tar.gz -C target/release $BIN_NAME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./rusty-rolodex-${{ github.ref_name }}-ubuntu-x86_64.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
