name: Rust Rolodex CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Rust toolchain
      uses: dtolnay/rust-toolchain@stable # Or rust-lang/setup-rust@v1 if preferred

    - name: Build
      run: cargo build --verbose

    - name: Add Cargo-fmt
      run: rustup component add rustfmt

    - name: Add Cargo-clippy
      run: rustup component add clippy

    - name: Check formatting
      run: cargo fmt --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings

    - name: Run tests
      run: cargo test --verbose